image: node:14.15.3
stages:
  - build
  - test

job1:
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry http://registry.npmjs.org/
    - npm install
    - npm start
  stage: test
    - npm run coverage
